### ISSUE TITLE
wxxd-fxrest/Alarm

### ISSUE THREAD

**Issue by wxxd-fxrest** [Team-Googling/WakeUpClock#15]
## 작업 내용
Alarm 기능 구현 

### to-do
- [ ] 임시 데이터 바인딩
- [ ] 스위치 버튼 기능 구현 
- [ ] 선택된 날짜(반복되는 요일) 색 변경
