### ISSUE TITLE
yyujnn/StopwatchLap

### ISSUE THREAD

**Issue by yyujnn** [Team-Googling/WakeUpClock#16]
## 작업 내용
랩 타임 기능 구현하기
랩 타임 기록 복사하기

### to-do

- [x] 테이블뷰에 record 타임 추가
- [x] 테이블뷰에 lap 타임 추가
- [x] 복사 기능 추가
