### ISSUE TITLE
limlogging/newAlarmPage

### ISSUE THREAD

**Issue by limlogging** [Team-Googling/WakeUpClock#22]
## 작업 내용
- 코어데이터 생성, 엔티티 추가, 알람 추가 페이지 UI 수정 

### to-do

- [ ] 알람 추가 페이지 UI 수정 
- [ ] 코어데이터 생성 
- [ ] 엔티티 추가 MyAlarm 
- [ ] 앱델리게이트 파일 수정
