### ISSUE TITLE
wxxd-fxrest/Navigation-Tab

### ISSUE THREAD

**Issue by wxxd-fxrest** [Team-Googling/WakeUpClock#29]
## 작업 내용
상하단 네비게이션, 탭바 디테일 수정 

### to-do
- [x] 알람 페이지 전체 코드 정리 
- [x] 상단 네비게이션 바 더보기 버튼 플러스 버튼으로 수정 
- [x] 상하단 네비게이션 바 스크롤 시 색상 변경되는 부분 수정 
- [x] 상하단 네비게이션 아이콘 다크/라이트 모드에 따라 스타일 변경
- [x] 다크/라이트 모드는 시스템 스타일을 따르는 게 아닌, 앱 내부에서 수동 설정한 값을 UserDefaults에 저장
